"""empty message

Revision ID: 0568af2ebff7
Revises: 5adf48254871
Create Date: 2022-12-08 13:26:23.164081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0568af2ebff7'
down_revision = '5adf48254871'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
