"""empty message

Revision ID: 1bc11f7eb7f4
Revises: 8b3c0d27d074
Create Date: 2022-12-08 16:10:34.394662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc11f7eb7f4'
down_revision = '8b3c0d27d074'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
