"""empty message

Revision ID: 37d402d6d5e8
Revises: 1cbecdcc402d
Create Date: 2022-12-08 15:22:14.286540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37d402d6d5e8'
down_revision = '1cbecdcc402d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completedquiz',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quiz_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('completedquestion',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('completed_quiz_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('question_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['completed_quiz_id'], ['completedquiz.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completedquestion')
    op.drop_table('completedquiz')
    # ### end Alembic commands ###
