"""empty message

Revision ID: 582b9383c708
Revises: c13991be190d
Create Date: 2022-12-08 12:19:24.117185

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "582b9383c708"
down_revision = "c13991be190d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    questiontypes = postgresql.ENUM("TEXTAREA", "RANGE", name="questiontypes")
    questiontypes.create(op.get_bind())
    op.add_column(
        "question",
        sa.Column(
            "type", sa.Enum("TEXTAREA", "RANGE", name="questiontypes"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "type")
    # ### end Alembic commands ###
