"""empty message

Revision ID: 5adf48254871
Revises: eebd90e3b3d5
Create Date: 2022-12-08 12:41:16.840295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adf48254871'
down_revision = 'eebd90e3b3d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('feature', sa.String(), nullable=True))
    op.add_column('question', sa.Column('min_label', sa.String(), nullable=True))
    op.add_column('question', sa.Column('max_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'max_label')
    op.drop_column('question', 'min_label')
    op.drop_column('question', 'feature')
    # ### end Alembic commands ###
