"""empty message

Revision ID: 8b3c0d27d074
Revises: 37d402d6d5e8
Create Date: 2022-12-08 15:37:11.371195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3c0d27d074'
down_revision = '37d402d6d5e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completedquestion', sa.Column('type', sa.Enum('TEXTAREA', 'RANGE', name='questiontypes'), nullable=False))
    op.add_column('completedquestion', sa.Column('text', sa.String(), nullable=True))
    op.add_column('completedquestion', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('completedquestion', sa.Column('feature', sa.String(), nullable=True))
    op.add_column('completedquestion', sa.Column('min_label', sa.String(), nullable=True))
    op.add_column('completedquestion', sa.Column('max_label', sa.String(), nullable=True))
    op.add_column('completedquiz', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completedquiz', 'name')
    op.drop_column('completedquestion', 'max_label')
    op.drop_column('completedquestion', 'min_label')
    op.drop_column('completedquestion', 'feature')
    op.drop_column('completedquestion', 'order')
    op.drop_column('completedquestion', 'text')
    op.drop_column('completedquestion', 'type')
    # ### end Alembic commands ###
