"""empty message

Revision ID: a4c167ef170f
Revises: af91341a1831
Create Date: 2022-12-08 18:02:54.260792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c167ef170f'
down_revision = 'af91341a1831'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('diagnosis', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'diagnosis')
    op.drop_column('user', 'name')
    op.drop_column('user', 'birthdate')
    # ### end Alembic commands ###
