"""empty message

Revision ID: af91341a1831
Revises: 2322e4e5ff4b
Create Date: 2022-12-08 17:25:03.541004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af91341a1831'
down_revision = '2322e4e5ff4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completedquestion', sa.Column('min_value', sa.Float(), nullable=True))
    op.add_column('completedquestion', sa.Column('max_value', sa.Float(), nullable=True))
    op.add_column('question', sa.Column('min_value', sa.Float(), nullable=True))
    op.add_column('question', sa.Column('max_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'max_value')
    op.drop_column('question', 'min_value')
    op.drop_column('completedquestion', 'max_value')
    op.drop_column('completedquestion', 'min_value')
    # ### end Alembic commands ###
