"""empty message

Revision ID: c13991be190d
Revises: 1240f591f541
Create Date: 2022-12-08 12:18:52.766798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13991be190d'
down_revision = '1240f591f541'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
